language: python
python: 3.4
cache: pip
env:
    - TOX_ENV=py27-18
    - TOX_ENV=py27-19
    - TOX_ENV=py27-110
    - TOX_ENV=py33-18
    - TOX_ENV=py34-18
    - TOX_ENV=py34-19
    - TOX_ENV=py34-110
    - TOX_ENV=py35-18
    - TOX_ENV=py35-19
    - TOX_ENV=py35-110
install:
    - pip install tox
script:
    - tox -e $TOX_ENV

